services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
